# Generated by Django 6.0.4 on 2026-04-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_remove_flashcard_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, verbose_name='Từ vựng')),
                ('meaning', models.TextField(verbose_name='Ý nghĩa')),
                ('language', models.CharField(choices=[('en', 'Tiếng Anh'), ('zh', 'Tiếng Trung'), ('ko', 'Tiếng Hàn')], default='en', max_length=2, verbose_name='Ngôn ngữ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
