# Generated by Django 6.0.4 on 2026-04-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_dictionaryword'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='energy',
            field=models.IntegerField(default=100),
        ),
    ]
